// BNO-055 Calibration data for Homeground
#define CALIBRATION_ACCEL_OFFSET_X -28 
#define CALIBRATION_ACCEL_OFFSET_Y 27 
#define CALIBRATION_ACCEL_OFFSET_Z -35 
#define CALIBRATION_GYRO_OFFSET_X -2 
#define CALIBRATION_GYRO_OFFSET_Y 1 
#define CALIBRATION_GYRO_OFFSET_Z 2 
#define CALIBRATION_MAG_OFFSET_Z -35 
#define CALIBRATION_MAG_OFFSET_X -2 
#define CALIBRATION_MAG_OFFSET_Y 1 
#define CALIBRATION_ACCEL_RADIUS 1000 
#define CALIBRATION_MAG_RADIUS 759
